[package]
name = "siaki"
version = "0.1.0"
authors = ["Jos√© F. Rives <jose@digio.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
